filebeat.inputs:
  - type: filestream
    id: docker-compose-logs
    enabled: true
  
    paths:
      - /var/lib/docker/containers/*/*.log

    parsers:
      - container:
          stream: all
          format: docker
    
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              equals:
                container.name: "pulse-app"
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true
          add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
